apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thinknyxdemoagain
  name: thinknyxdemoagain
  namespace: yogeshtestagain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thinknyxdemoagain
  template:
    metadata:
      labels:
        app: thinknyxdemoagain
    spec:
      containers:
      - image: yogeshraheja/devopsinaction:v1
        name: devopsinactionagain
